#!/bin/bash

for ((i=0; i<=$2; i++)) do
 wget -q -O- http://boards.4chan.org/$1/$i | sed -e 's/href/\n/g' | grep -A1 omitted | grep "here</a> to view" | cut -d'"' -f2 | cut -d/ -f2 | sort -u >> threads
done
procs=0
while read line; do
wget -e robots=off  -nvcdp -t 0 -Hkrl 0 -I "$1" -A jpg,jpeg,gif,tif,png -R *s.*  -P images/$line "boards.4chan.org/$1/res/$line" & 
	procs=$[$procs + 1]; [ $procs = 6 ] && { wait; procs=0; }
done < threads ; wait
rm threads
